### ISSUE TITLE
CONFIGMAP  hwameistor-scheduler-config need to be updated

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/local-disk-manager#82] opened 2022-06-20 09:34 UTC
![图片](https://user-images.githubusercontent.com/76234281/174572294-8bc37844-9aa0-4ec9-b3cc-68e76c1fc0aa.png)
![图片](https://user-images.githubusercontent.com/76234281/174572425-1b60c750-7351-456d-94bc-b8a980f720d4.png)

**Comment by SSmallMonster** [comment] 2022-06-23 01:52
The error is caused by missing the reserve plugin in SchedulerConfiguration.

It has been fixed in https://github.com/hwameistor/helm-charts/pull/55

**Closed by SSmallMonster** 2022-06-23 01:52 UTC
Labels: bug
